version: '3.7'
services:
  main:
    container_name: main
    build: 
      context: .
    env_file:
      .env 
    volumes:
      - .:/app
      - /app/node_modules
    ports: 
      - 5000:5000
      - 9229:9229
    command: npm start
    depends_on:
      - mongodb
    restart: always
  mongodb:
    container_name: mongodb
    image: mongo:4.4.13
    # environment:
      # MONGO_INITDB_ROOT_USERNAME: root
      # MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
    volumes: 
      - mongodb_data_container:/data/db
    restart: always
  
volumes:
  mongodb_data_container:
      
    

# version: '3.7'
# services:
#   mongodb_container:
#     image: mongo:4.4.13
#     environment:
#       MONGO_INITDB_ROOT_USERNAME: root
#       MONGO_INITDB_ROOT_PASSWORD: rootpassword
#     ports:
#       - 27017:27017
#     volumes:
#       - mongodb_data_container:/data/db


# volumes:
#   mongodb_data_container: 




# version: '3.0'

# services:
#   main:
#     container_name: main
#     build:
#       context: .
#     env_file:
#       - .development.env
#     volumes:
#       - .:/app
#       - /app/node_modules
#     ports:
#       - 5000:5000
#       - 9229:9229
#     command: npm run start:dev
#     depends_on:
#       - postgres
#     restart: always
#   postgres:
#     container_name: postgres
#     image: postgres:12
#     env_file:
#       - .development.env
#     environment:
#       PG_DATA: /var/lib/postgresql/data
#     ports:
#       - 5432:5432
#     volumes:
#       - pgdata:/var/lib/postgresql/data
#     restart: always

# volumes:
#   pgdata: